# Generated by Django 2.2.5 on 2019-11-22 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_program'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Program',
        ),
    ]
