# Generated by Django 2.2.5 on 2019-11-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_delete_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stevilo_prevzemov', models.IntegerField(default=0)),
                ('stevilo_odpisov', models.IntegerField(default=0)),
                ('stevilo_faktur', models.IntegerField(default=0)),
                ('stevilo_racunov', models.IntegerField(default=0)),
                ('stevilo_inventur', models.IntegerField(default=0)),
            ],
        ),
    ]
