# Generated by Django 2.2.5 on 2020-01-20 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0049_remove_stranka_stevilo'),
        ('program', '0004_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='stranka',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='prodaja.Stranka'),
        ),
    ]
