# Generated by Django 2.2.5 on 2020-05-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_profil_stranka'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='celo_ime',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='profil',
            name='stevilka_racuna',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='profil',
            name='tip_banke',
            field=models.CharField(default='', max_length=40),
        ),
    ]
