# Generated by Django 2.2.5 on 2020-08-30 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0072_auto_20200830_0907'),
        ('program', '0007_profil_telefon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='aktivna_zaloga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Zaloga'),
        ),
        migrations.AddField(
            model_name='profil',
            name='dovoljene_zaloge',
            field=models.ManyToManyField(related_name='dovoljene', to='zaloga.Zaloga'),
        ),
    ]
