# Generated by Django 2.2.5 on 2020-09-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0008_auto_20200830_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='stevilo_prenosov',
            field=models.IntegerField(default=0),
        ),
    ]
