# Generated by Django 2.2.16 on 2021-07-17 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0009_program_stevilo_prenosov'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drzava',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(default='', max_length=30)),
                ('kratica', models.CharField(default='', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Oseba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(default='/', max_length=3)),
                ('priimek', models.CharField(default='/', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='profil',
            name='dovoljene_zaloge',
        ),
        migrations.AlterField(
            model_name='profil',
            name='aktivna_zaloga',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Podjetje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(default='/', max_length=30)),
                ('direktor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='program.Oseba')),
                ('drzava', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='program.Drzava')),
            ],
        ),
    ]
