# Generated by Django 2.2.16 on 2021-07-31 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0010_auto_20210717_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='oseba',
            name='davcna',
            field=models.CharField(default='/', max_length=30),
        ),
        migrations.AddField(
            model_name='oseba',
            name='drzava',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.Drzava'),
        ),
        migrations.AddField(
            model_name='oseba',
            name='mail',
            field=models.CharField(default='/', max_length=40),
        ),
        migrations.AddField(
            model_name='oseba',
            name='mesto',
            field=models.CharField(default='/', max_length=40),
        ),
        migrations.AddField(
            model_name='oseba',
            name='telefon',
            field=models.CharField(default='/', max_length=20),
        ),
        migrations.AddField(
            model_name='oseba',
            name='ulica',
            field=models.CharField(default='/', max_length=40),
        ),
    ]
