# Generated by Django 2.2.16 on 2021-08-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0011_auto_20210731_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(default='/', max_length=30)),
                ('simbol', models.CharField(default='/', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
