# Generated by Django 2.2.16 on 2021-08-12 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0012_valuta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='stranka',
        ),
    ]
