# Generated by Django 2.2.5 on 2019-09-16 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zaloga', '0012_sprememba_datum_spremembe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prodaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zaloga', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Zaloga')),
            ],
        ),
        migrations.CreateModel(
            name='Stranka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(default='', max_length=30)),
                ('telefon', models.CharField(default='', max_length=20)),
                ('mail', models.EmailField(default='', max_length=254)),
                ('prodaja', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='prodaja.Prodaja')),
            ],
        ),
    ]
