# Generated by Django 2.2.5 on 2019-09-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodaja',
            name='title',
            field=models.CharField(default='prodaja', max_length=10),
        ),
    ]
