# Generated by Django 2.2.5 on 2019-09-16 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0002_prodaja_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stranka',
            name='prodaja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prodaja.Prodaja'),
        ),
    ]
