# Generated by Django 2.2.5 on 2019-09-17 10:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0003_auto_20190916_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dnevna_prodaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(default=django.utils.timezone.now)),
                ('prodaja', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prodaja.Prodaja')),
            ],
        ),
        migrations.CreateModel(
            name='Vele_prodaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(default=django.utils.timezone.now)),
                ('prodaja', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prodaja.Prodaja')),
                ('stranka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodaja.Stranka')),
            ],
        ),
        migrations.CreateModel(
            name='Racun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cas', models.TimeField(default=django.utils.timezone.now)),
                ('dnevna_prodaja', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prodaja.Dnevna_prodaja')),
            ],
        ),
    ]
