# Generated by Django 2.2.5 on 2019-09-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0004_dnevna_prodaja_racun_vele_prodaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='racun',
            name='cena',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True),
        ),
    ]
