# Generated by Django 2.2.5 on 2019-09-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0005_racun_cena'),
    ]

    operations = [
        migrations.AddField(
            model_name='stranka',
            name='status',
            field=models.CharField(default='aktivno', max_length=10),
        ),
    ]
