# Generated by Django 2.2.5 on 2019-09-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0006_stranka_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stranka',
            name='skupna_cena_kupljenih',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='stranka',
            name='stevilo_kupljenih',
            field=models.IntegerField(default=0),
        ),
    ]
