# Generated by Django 2.2.5 on 2019-09-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0008_auto_20190919_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='vele_prodaja',
            name='status',
            field=models.CharField(default='aktivno', max_length=10),
        ),
    ]
