# Generated by Django 2.2.5 on 2019-09-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0009_vele_prodaja_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vele_prodaja',
            name='title',
            field=models.CharField(default='vele_prodaja', max_length=10),
        ),
    ]
