# Generated by Django 2.2.5 on 2019-09-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0010_vele_prodaja_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnevna_prodaja',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
