# Generated by Django 2.2.5 on 2019-09-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0011_dnevna_prodaja_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='racun',
            name='popust',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='racun',
            name='status',
            field=models.CharField(default='aktivno', max_length=10),
        ),
        migrations.AlterField(
            model_name='racun',
            name='cas',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
