# Generated by Django 2.2.5 on 2019-10-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0012_auto_20190928_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racun',
            name='cena',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
    ]
