# Generated by Django 2.2.5 on 2019-10-04 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0013_auto_20191004_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racun',
            name='cena',
        ),
    ]
