# Generated by Django 2.2.5 on 2019-10-11 17:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0014_remove_racun_cena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnevna_prodaja',
            name='datum',
            field=models.DateField(default=datetime.datetime(2019, 10, 11, 17, 35, 10, 450005, tzinfo=utc)),
        ),
    ]
