# Generated by Django 2.2.5 on 2019-10-16 14:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0017_auto_20191016_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnevna_prodaja',
            name='datum',
            field=models.DateField(default=datetime.datetime(2019, 10, 16, 14, 22, 17, 593149, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vele_prodaja',
            name='datum',
            field=models.DateField(default=datetime.datetime(2019, 10, 16, 14, 22, 19, 846546, tzinfo=utc)),
        ),
    ]
