# Generated by Django 2.2.5 on 2019-10-17 20:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0020_auto_20191017_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnevna_prodaja',
            name='naslov',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='dnevna_prodaja',
            name='datum',
            field=models.DateField(default=datetime.datetime(2019, 10, 17, 20, 8, 58, 522598, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vele_prodaja',
            name='datum',
            field=models.DateField(default=datetime.datetime(2019, 10, 17, 20, 8, 58, 705122, tzinfo=utc)),
        ),
    ]
