# Generated by Django 2.2.5 on 2019-10-17 20:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0021_auto_20191017_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnevna_prodaja',
            name='naslov',
        ),
        migrations.RemoveField(
            model_name='prodaja',
            name='zaloga',
        ),
        migrations.AlterField(
            model_name='dnevna_prodaja',
            name='datum',
            field=models.DateField(default=datetime.datetime(2019, 10, 17, 20, 11, 45, 367707, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vele_prodaja',
            name='datum',
            field=models.DateField(default=datetime.datetime(2019, 10, 17, 20, 11, 45, 513034, tzinfo=utc)),
        ),
    ]
