# Generated by Django 2.2.5 on 2019-10-17 20:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0024_auto_20191017_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnevna_prodaja',
            name='datum',
            field=models.DateField(default=datetime.datetime(2019, 10, 17, 20, 15, 14, 194522, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dnevna_prodaja',
            name='prodaja',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='prodaja.Prodaja'),
        ),
        migrations.AlterField(
            model_name='stranka',
            name='prodaja',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='prodaja.Prodaja'),
        ),
        migrations.AlterField(
            model_name='vele_prodaja',
            name='datum',
            field=models.DateField(default=datetime.datetime(2019, 10, 17, 20, 15, 14, 346136, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vele_prodaja',
            name='prodaja',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='prodaja.Prodaja'),
        ),
    ]
