# Generated by Django 2.2.5 on 2019-10-17 20:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0028_auto_20191017_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodaja',
            name='zaloga',
        ),
        migrations.AlterField(
            model_name='dnevna_prodaja',
            name='datum',
            field=models.DateField(default=datetime.datetime(2019, 10, 17, 20, 27, 8, 206604, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prodaja',
            name='title',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='vele_prodaja',
            name='datum',
            field=models.DateField(default=datetime.datetime(2019, 10, 17, 20, 27, 8, 207100, tzinfo=utc)),
        ),
    ]
