# Generated by Django 2.2.5 on 2019-10-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0030_auto_20191017_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=10)),
                ('stevilo_faktur', models.IntegerField(default=0)),
                ('stevilo_racunov', models.IntegerField(default=0)),
            ],
        ),
    ]
