# Generated by Django 2.2.5 on 2019-10-17 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0031_prod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prod',
        ),
        migrations.RemoveField(
            model_name='dnevna_prodaja',
            name='prodaja',
        ),
        migrations.RemoveField(
            model_name='stranka',
            name='prodaja',
        ),
        migrations.RemoveField(
            model_name='vele_prodaja',
            name='prodaja',
        ),
        migrations.DeleteModel(
            name='Prodaja',
        ),
    ]
