# Generated by Django 2.2.5 on 2019-10-17 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0022_auto_20191016_1622'),
        ('prodaja', '0032_auto_20191017_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prodaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='prodaja', max_length=30)),
                ('stevilo_faktur', models.IntegerField(default=0)),
                ('stevilo_racunov', models.IntegerField(default=0)),
                ('zaloga', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Zaloga')),
            ],
        ),
    ]
