# Generated by Django 2.2.5 on 2019-10-17 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0033_prodaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnevna_prodaja',
            name='prodaja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prodaja.Prodaja'),
        ),
        migrations.AddField(
            model_name='racun',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='stranka',
            name='prodaja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prodaja.Prodaja'),
        ),
        migrations.AddField(
            model_name='vele_prodaja',
            name='prodaja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prodaja.Prodaja'),
        ),
    ]
