# Generated by Django 2.2.5 on 2019-10-29 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0028_prevzem_kontejner'),
        ('prodaja', '0035_vele_prodaja_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='vele_prodaja',
            name='zaloga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Zaloga'),
        ),
    ]
