# Generated by Django 2.2.5 on 2019-11-03 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0028_prevzem_kontejner'),
        ('prodaja', '0036_vele_prodaja_zaloga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tip', models.CharField(choices=[('Y', 'yellow'), ('W', 'white'), ('JP40', 'Japan_40%'), ('JP70', 'Japan_70%')], default='Y', max_length=4)),
                ('tip_prodaje', models.CharField(choices=[('dnevna_prodaja', 'Dnevna_prodaja'), ('vele_prodaja', 'Vele_prodaja')], default='vele_prodaja', max_length=15)),
                ('sestavina', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Sestavina')),
            ],
        ),
    ]
