# Generated by Django 2.2.5 on 2019-11-03 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0037_cena'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cena',
            old_name='tip_prodaje',
            new_name='prodaja',
        ),
    ]
