# Generated by Django 2.2.5 on 2019-11-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0038_auto_20191103_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='vele_prodaja',
            name='popust',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
