# Generated by Django 2.2.5 on 2019-11-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0039_vele_prodaja_popust'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodaja',
            name='zaloga',
        ),
        migrations.RemoveField(
            model_name='vele_prodaja',
            name='zaloga',
        ),
        migrations.DeleteModel(
            name='Cena',
        ),
    ]
