# Generated by Django 2.2.5 on 2019-11-22 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0041_auto_20191111_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Naslov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drzava', models.CharField(default='', max_length=20)),
                ('mesto', models.CharField(default='', max_length=20)),
                ('naslov', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='stranka',
            name='davcna',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='stranka',
            name='naziv',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='stranka',
            name='mail',
            field=models.CharField(default='/', max_length=40),
        ),
        migrations.AlterField(
            model_name='stranka',
            name='telefon',
            field=models.CharField(default='/', max_length=20),
        ),
        migrations.AddField(
            model_name='stranka',
            name='naslov',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='prodaja.Naslov'),
        ),
    ]
