# Generated by Django 2.2.5 on 2019-11-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0042_auto_20191122_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stranka',
            name='davcna',
        ),
        migrations.RemoveField(
            model_name='stranka',
            name='naslov',
        ),
        migrations.RemoveField(
            model_name='stranka',
            name='naziv',
        ),
        migrations.AlterField(
            model_name='stranka',
            name='mail',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='stranka',
            name='telefon',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='Naslov',
        ),
    ]
