# Generated by Django 2.2.5 on 2019-11-22 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0044_auto_20191122_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnevna_prodaja',
            name='prodaja',
        ),
    ]
