# Generated by Django 2.2.5 on 2019-11-22 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0045_remove_dnevna_prodaja_prodaja'),
        ('zaloga', '0047_auto_20191122_2012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dnevna_prodaja',
        ),
    ]
