# Generated by Django 2.2.5 on 2020-01-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0047_naslov_stevilo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naslov',
            name='stevilo',
        ),
        migrations.AddField(
            model_name='stranka',
            name='stevilo',
            field=models.IntegerField(default=0),
        ),
    ]
