# Generated by Django 2.2.5 on 2020-01-05 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0048_auto_20200105_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stranka',
            name='stevilo',
        ),
    ]
