# Generated by Django 3.2.8 on 2022-06-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0049_remove_stranka_stevilo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skupina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
