# Generated by Django 2.2.16 on 2021-08-12 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0013_remove_profil_stranka'),
        ('prodaja', '0049_remove_stranka_stevilo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stranka',
            name='naslov',
        ),
        migrations.RemoveField(
            model_name='stranka',
            name='prodaja',
        ),
        migrations.DeleteModel(
            name='Naslov',
        ),
        migrations.DeleteModel(
            name='Prodaja',
        ),
        migrations.DeleteModel(
            name='Stranka',
        ),
    ]
