# Generated by Django 3.2.8 on 2022-06-16 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0050_skupina'),
    ]

    operations = [
        migrations.AddField(
            model_name='stranka',
            name='skupina',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prodaja.skupina'),
        ),
    ]
