# Generated by Django 3.2.16 on 2022-10-19 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(default='/', max_length=30)),
                ('tip', models.CharField(default='/', max_length=30)),
                ('status', models.CharField(default='aktivno', max_length=30)),
                ('datum', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Dimenzija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radij', models.CharField(default='/', max_length=30)),
                ('sirina', models.CharField(default='/', max_length=30)),
                ('visina', models.CharField(default='/', max_length=30)),
                ('special', models.BooleanField(default=False)),
                ('dimenzija', models.CharField(default='/', max_length=30)),
            ],
            options={
                'ordering': ['radij', 'visina', 'sirina', 'special'],
            },
        ),
        migrations.CreateModel(
            name='LastnostSestavine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(default='TRDOTA', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Paket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cas', models.DateTimeField()),
                ('isModel', models.BooleanField(default=False)),
                ('baza', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proizvodnja.baza')),
            ],
        ),
        migrations.CreateModel(
            name='Podjetje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(default='/', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PoslovnaEnota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(default='/', max_length=50)),
                ('podjetje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proizvodnja.podjetje')),
            ],
        ),
        migrations.CreateModel(
            name='Sestavina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(default='/', max_length=30)),
                ('dimenzija', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='proizvodnja.dimenzija')),
                ('lastnosti', models.ManyToManyField(to='proizvodnja.LastnostSestavine')),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(default='/', max_length=30)),
                ('kratica', models.CharField(default='/', max_length=5)),
                ('barva', models.CharField(default='yellow', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VnosDimenzijePaketa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimenzija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proizvodnja.dimenzija')),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proizvodnja.paket')),
            ],
        ),
        migrations.CreateModel(
            name='Zaloga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(default='/', max_length=30)),
                ('poslovnaEnota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proizvodnja.poslovnaenota')),
            ],
        ),
        migrations.CreateModel(
            name='VnosZaloge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.FloatField(default=0)),
                ('lastnostSestavine', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vnosi_zaloge', to='proizvodnja.lastnostsestavine')),
                ('sestavina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vnosi_zaloge', to='proizvodnja.sestavina')),
                ('zaloga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vnosi', to='proizvodnja.zaloga')),
            ],
        ),
        migrations.CreateModel(
            name='VnosTipaPaketa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.IntegerField(default=0)),
                ('tip', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proizvodnja.tip')),
                ('vnosDimenzijePaketa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proizvodnja.vnosdimenzijepaketa')),
            ],
        ),
        migrations.CreateModel(
            name='VnosBaze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stevilo', models.IntegerField(default=0)),
                ('cas', models.DateTimeField(blank=True, default=None, null=True)),
                ('baza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vnosi', to='proizvodnja.baza')),
                ('lastnostSestavine', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proizvodnja.lastnostsestavine')),
                ('paket', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='proizvodnja.vnostipapaketa')),
                ('sestavina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proizvodnja.sestavina')),
            ],
        ),
        migrations.CreateModel(
            name='SpremembaZaloge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprememba', models.FloatField()),
                ('fiks', models.BooleanField(default=False)),
                ('cas', models.DateTimeField()),
                ('vnos_baze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proizvodnja.vnosbaze')),
                ('vnos_zaloge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proizvodnja.vnoszaloge')),
            ],
        ),
        migrations.AddField(
            model_name='sestavina',
            name='tip',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='proizvodnja.tip'),
        ),
        migrations.AddField(
            model_name='baza',
            name='zaloga',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proizvodnja.zaloga'),
        ),
    ]
