# Generated by Django 2.2.5 on 2019-09-10 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimenzija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimenzija', models.CharField(default='', max_length=20)),
                ('radius', models.CharField(max_length=10)),
                ('height', models.CharField(max_length=10)),
                ('width', models.CharField(max_length=10)),
                ('special', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['radius', 'height', 'width', 'special'],
            },
        ),
        migrations.CreateModel(
            name='Sestavina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yellow', models.IntegerField()),
                ('white', models.IntegerField()),
                ('dimenzija', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='zaloga.Dimenzija')),
                ('zaloga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zaloga.Zaloga')),
            ],
            options={
                'ordering': ['dimenzija'],
            },
        ),
    ]
