# Generated by Django 2.2.5 on 2019-09-10 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0002_dimenzija_sestavina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprememba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_spremembe', models.CharField(default='', max_length=20)),
                ('stevilo', models.IntegerField(default=0)),
                ('tip', models.CharField(default='', max_length=10)),
                ('sestavina', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Sestavina')),
                ('zaloga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zaloga.Zaloga')),
            ],
        ),
    ]
