# Generated by Django 2.2.5 on 2019-09-10 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0004_inventura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventura',
            name='status',
        ),
        migrations.CreateModel(
            name='Vnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(default='yellow', max_length=10)),
                ('stevilo', models.IntegerField()),
                ('dimenzija', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='zaloga.Dimenzija')),
                ('inventura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zaloga.Inventura')),
            ],
        ),
    ]
