# Generated by Django 2.2.5 on 2019-09-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0005_auto_20190910_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventura',
            name='status',
            field=models.CharField(default='aktivno', max_length=10),
        ),
    ]
