# Generated by Django 2.2.5 on 2019-09-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0006_inventura_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vnos',
            name='dimenzija',
            field=models.CharField(default='', max_length=10),
        ),
    ]
