# Generated by Django 2.2.5 on 2019-09-15 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0009_auto_20190914_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprememba',
            name='inventura',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Inventura'),
        ),
        migrations.AddField(
            model_name='sprememba',
            name='odpis',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Odpis'),
        ),
        migrations.AddField(
            model_name='sprememba',
            name='prevzem',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Prevzem'),
        ),
        migrations.AlterField(
            model_name='sprememba',
            name='zaloga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Zaloga'),
        ),
    ]
