# Generated by Django 2.2.5 on 2019-09-15 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0011_sprememba_stanje_po_spremembi'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprememba',
            name='datum_spremembe',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
