# Generated by Django 2.2.5 on 2019-09-17 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('zaloga', '0012_sprememba_datum_spremembe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprememba',
            name='inventura',
        ),
        migrations.RemoveField(
            model_name='sprememba',
            name='odpis',
        ),
        migrations.RemoveField(
            model_name='sprememba',
            name='prevzem',
        ),
        migrations.RemoveField(
            model_name='vnos',
            name='inventura',
        ),
        migrations.RemoveField(
            model_name='vnos',
            name='odpis',
        ),
        migrations.RemoveField(
            model_name='vnos',
            name='prevzem',
        ),
        migrations.AddField(
            model_name='sprememba',
            name='content_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='sprememba',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vnos',
            name='content_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='vnos',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
