# Generated by Django 2.2.5 on 2019-09-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0014_auto_20190919_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='vnos',
            name='cena',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True),
        ),
    ]
