# Generated by Django 2.2.5 on 2019-09-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0015_vnos_cena'),
    ]

    operations = [
        migrations.AddField(
            model_name='vnos',
            name='skupna_cena',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True),
        ),
    ]
