# Generated by Django 2.2.5 on 2019-10-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0017_inventura_vnos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sestavina',
            name='dnevna_prodaja_white',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sestavina',
            name='dnevna_prodaja_yellow',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sestavina',
            name='vele_prodaja_white',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sestavina',
            name='vele_prodaja_yellow',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sestavina',
            name='white',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sestavina',
            name='yellow',
            field=models.IntegerField(default=0),
        ),
    ]
