# Generated by Django 2.2.5 on 2019-10-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0018_auto_20191004_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vnos',
            name='cena',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='vnos',
            name='skupna_cena',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
    ]
