# Generated by Django 2.2.5 on 2019-10-11 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0019_auto_20191004_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vnos',
            name='skupna_cena',
        ),
    ]
