# Generated by Django 2.2.5 on 2019-10-16 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0020_remove_vnos_skupna_cena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprememba',
            name='stanje_po_spremembi',
        ),
        migrations.AddField(
            model_name='sprememba',
            name='sprememba_zaloge',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vnos',
            name='sprememba',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='zaloga.Sprememba'),
        ),
    ]
