# Generated by Django 2.2.5 on 2019-10-16 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0021_auto_20191016_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vnos',
            name='sprememba',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Sprememba'),
        ),
    ]
