# Generated by Django 2.2.5 on 2019-10-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0022_auto_20191016_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprememba',
            name='stanje',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
