# Generated by Django 2.2.5 on 2019-10-29 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0025_auto_20191029_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prevzem',
            name='kontejner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Kontejner'),
        ),
    ]
