# Generated by Django 2.2.5 on 2019-10-29 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0026_auto_20191029_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prevzem',
            name='kontejner',
        ),
    ]
