# Generated by Django 2.2.5 on 2019-10-29 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0027_remove_prevzem_kontejner'),
    ]

    operations = [
        migrations.AddField(
            model_name='prevzem',
            name='kontejner',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Kontejner'),
        ),
    ]
