# Generated by Django 2.2.5 on 2019-11-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0028_prevzem_kontejner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sestavina',
            name='dnevna_prodaja_white',
        ),
        migrations.RemoveField(
            model_name='sestavina',
            name='dnevna_prodaja_yellow',
        ),
        migrations.RemoveField(
            model_name='sestavina',
            name='vele_prodaja_white',
        ),
        migrations.RemoveField(
            model_name='sestavina',
            name='vele_prodaja_yellow',
        ),
    ]
