# Generated by Django 2.2.5 on 2019-11-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0029_auto_20191103_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='sestavina',
            name='JP40',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sestavina',
            name='JP70',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sprememba',
            name='tip',
            field=models.CharField(choices=[('Y', 'yellow'), ('W', 'white'), ('JP40', 'Japan_40%'), ('JP70', 'Japan_70%')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='sprememba',
            name='tip_spremembe',
            field=models.CharField(choices=[('inventura', 'Inventura'), ('prevzem', 'Prevzem'), ('odpis', 'Odpis'), ('vele_prodaja', 'Vele prodaja'), ('dnevna_prodaja', 'Dnevna prodaja')], default='', max_length=20),
        ),
    ]
