# Generated by Django 2.2.5 on 2019-11-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0030_auto_20191105_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vnos',
            name='tip',
            field=models.CharField(choices=[('Y', 'yellow'), ('W', 'white'), ('JP40', 'Japan_40%'), ('JP70', 'Japan_70%')], default='Y', max_length=10),
        ),
    ]
