# Generated by Django 2.2.5 on 2019-11-05 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0031_auto_20191105_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sestavina',
            old_name='white',
            new_name='W',
        ),
        migrations.RenameField(
            model_name='sestavina',
            old_name='yellow',
            new_name='Y',
        ),
    ]
