# Generated by Django 2.2.5 on 2019-11-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0032_auto_20191105_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprememba',
            name='tip',
            field=models.CharField(choices=[('Y', 'Yellow'), ('W', 'White'), ('JP40', 'Japan40%'), ('JP70', 'Japan70%')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='vnos',
            name='tip',
            field=models.CharField(choices=[('Y', 'Yellow'), ('W', 'White'), ('JP40', 'Japan40%'), ('JP70', 'Japan70%')], default='Y', max_length=10),
        ),
    ]
