# Generated by Django 2.2.5 on 2019-11-06 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0033_auto_20191105_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vnos',
            name='dimenzija',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Dimenzija'),
        ),
    ]
