# Generated by Django 2.2.5 on 2019-11-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0035_auto_20191110_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprememba',
            name='baza',
        ),
        migrations.AddField(
            model_name='sprememba',
            name='baza_id',
            field=models.IntegerField(default=0),
        ),
    ]
