# Generated by Django 2.2.5 on 2019-11-10 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('zaloga', '0037_auto_20191110_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baza',
            name='kontejner',
        ),
        migrations.RemoveField(
            model_name='vnos',
            name='baza',
        ),
        migrations.AddField(
            model_name='vnos',
            name='content_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='vnos',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='baza',
            name='sprememba_zaloge',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='baza',
            name='tip',
            field=models.CharField(choices=[('inventura', 'Inventura')], default='prevzem', max_length=20),
        ),
        migrations.CreateModel(
            name='Sprememba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stanje', models.IntegerField(blank=True, default=None, null=True)),
                ('object_id', models.PositiveIntegerField(default=0)),
                ('tip_spremembe', models.CharField(choices=[('inventura', 'Inventura'), ('prevzem', 'Prevzem'), ('odpis', 'Odpis'), ('vele_prodaja', 'Vele prodaja'), ('dnevna_prodaja', 'Dnevna prodaja')], default='', max_length=20)),
                ('stevilo', models.IntegerField(default=0)),
                ('tip', models.CharField(choices=[('Y', 'Yellow'), ('W', 'White'), ('JP40', 'Japan40%'), ('JP70', 'Japan70%')], default='', max_length=10)),
                ('sprememba_zaloge', models.IntegerField(default=1)),
                ('datum_spremembe', models.DateField(default=django.utils.timezone.now)),
                ('content_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('sestavina', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Sestavina')),
                ('zaloga', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Zaloga')),
            ],
        ),
        migrations.CreateModel(
            name='Prevzem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=15)),
                ('datum', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='aktivno', max_length=10)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kontejner', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Kontejner')),
                ('zaloga', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Zaloga')),
            ],
        ),
        migrations.CreateModel(
            name='Odpis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=15)),
                ('datum', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='aktivno', max_length=10)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zaloga', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Zaloga')),
            ],
        ),
        migrations.CreateModel(
            name='Inventura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=15)),
                ('datum', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='aktivno', max_length=10)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zaloga', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Zaloga')),
            ],
        ),
        migrations.AddField(
            model_name='vnos',
            name='sprememba',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Sprememba'),
        ),
    ]
