# Generated by Django 2.2.5 on 2019-11-10 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0038_auto_20191110_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odpis',
            name='author',
        ),
        migrations.RemoveField(
            model_name='odpis',
            name='zaloga',
        ),
        migrations.RemoveField(
            model_name='prevzem',
            name='author',
        ),
        migrations.RemoveField(
            model_name='prevzem',
            name='kontejner',
        ),
        migrations.RemoveField(
            model_name='prevzem',
            name='zaloga',
        ),
        migrations.RemoveField(
            model_name='sprememba',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='sprememba',
            name='datum_spremembe',
        ),
        migrations.RemoveField(
            model_name='sprememba',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='sprememba',
            name='sprememba_zaloge',
        ),
        migrations.RemoveField(
            model_name='sprememba',
            name='tip_spremembe',
        ),
        migrations.AddField(
            model_name='baza',
            name='kontejner',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Kontejner'),
        ),
        migrations.AddField(
            model_name='sprememba',
            name='baza',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Baza'),
        ),
        migrations.AlterField(
            model_name='baza',
            name='sprememba_zaloge',
            field=models.IntegerField(default=-1),
        ),
        migrations.DeleteModel(
            name='Inventura',
        ),
        migrations.DeleteModel(
            name='Odpis',
        ),
        migrations.DeleteModel(
            name='Prevzem',
        ),
    ]
