# Generated by Django 2.2.5 on 2019-11-10 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0039_auto_20191110_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vnos',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='vnos',
            name='object_id',
        ),
        migrations.AddField(
            model_name='vnos',
            name='baza',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Baza'),
        ),
        migrations.AlterField(
            model_name='baza',
            name='tip',
            field=models.CharField(choices=[('inventura', 'Inventura'), ('prevzem', 'Prevzem'), ('odpis', 'Odpis'), ('racun', 'Racun')], default='prevzem', max_length=20),
        ),
    ]
