# Generated by Django 2.2.5 on 2019-11-11 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0040_auto_20191110_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vnos',
            name='sprememba',
        ),
    ]
