# Generated by Django 2.2.5 on 2019-11-11 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0041_remove_vnos_sprememba'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tip', models.CharField(choices=[('Y', 'Yellow'), ('W', 'White'), ('JP40', 'Japan40%'), ('JP70', 'Japan70%')], default='Y', max_length=4)),
                ('prodaja', models.CharField(choices=[('dnevna_prodaja', 'Dnevna_prodaja'), ('vele_prodaja', 'Vele_prodaja')], default='vele_prodaja', max_length=15)),
                ('sestavina', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Sestavina')),
            ],
        ),
    ]
