# Generated by Django 2.2.5 on 2019-11-11 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0041_auto_20191111_1321'),
        ('zaloga', '0042_cena'),
    ]

    operations = [
        migrations.AddField(
            model_name='baza',
            name='cas',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='baza',
            name='dnevna_prodaja',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='prodaja.Dnevna_prodaja'),
        ),
        migrations.AddField(
            model_name='baza',
            name='popust',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='baza',
            name='stranka',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='prodaja.Stranka'),
        ),
    ]
