# Generated by Django 2.2.5 on 2019-11-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0043_auto_20191111_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baza',
            name='tip',
            field=models.CharField(choices=[('inventura', 'Inventura'), ('prevzem', 'Prevzem'), ('odpis', 'Odpis'), ('vele_prodaja', 'Vele prodaja'), ('racun', 'Racun')], default='prevzem', max_length=20),
        ),
    ]
