# Generated by Django 2.2.5 on 2019-11-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0044_auto_20191111_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='sestavina',
            name='JP50',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cena',
            name='tip',
            field=models.CharField(choices=[('Y', 'Yellow'), ('W', 'White'), ('JP40', 'Japan40%'), ('JP70', 'Japan70%'), ('JP50', 'Japan50%')], default='Y', max_length=4),
        ),
        migrations.AlterField(
            model_name='sprememba',
            name='tip',
            field=models.CharField(choices=[('Y', 'Yellow'), ('W', 'White'), ('JP40', 'Japan40%'), ('JP70', 'Japan70%'), ('JP50', 'Japan50%')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='vnos',
            name='tip',
            field=models.CharField(choices=[('Y', 'Yellow'), ('W', 'White'), ('JP40', 'Japan40%'), ('JP70', 'Japan70%'), ('JP50', 'Japan50%')], default='Y', max_length=10),
        ),
    ]
