# Generated by Django 2.2.5 on 2019-11-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0045_auto_20191117_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sestavina',
            old_name='JP40',
            new_name='JP',
        ),
        migrations.AlterField(
            model_name='cena',
            name='tip',
            field=models.CharField(choices=[('Y', 'Yellow'), ('W', 'White'), ('JP', 'Japan'), ('JP50', 'Japan50%'), ('JP70', 'Japan70%')], default='Y', max_length=4),
        ),
        migrations.AlterField(
            model_name='sprememba',
            name='tip',
            field=models.CharField(choices=[('Y', 'Yellow'), ('W', 'White'), ('JP', 'Japan'), ('JP50', 'Japan50%'), ('JP70', 'Japan70%')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='vnos',
            name='tip',
            field=models.CharField(choices=[('Y', 'Yellow'), ('W', 'White'), ('JP', 'Japan'), ('JP50', 'Japan50%'), ('JP70', 'Japan70%')], default='Y', max_length=10),
        ),
    ]
