# Generated by Django 2.2.5 on 2019-11-22 19:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prodaja', '0045_remove_dnevna_prodaja_prodaja'),
        ('zaloga', '0046_auto_20191122_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dnevna_prodaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(default='', max_length=20)),
                ('prodaja', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prodaja.Prodaja')),
            ],
        ),
        migrations.AlterField(
            model_name='baza',
            name='dnevna_prodaja',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Dnevna_prodaja'),
        ),
    ]
