# Generated by Django 2.2.5 on 2019-11-26 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0048_dnevna_prodaja_zaloga'),
    ]

    operations = [
        migrations.AddField(
            model_name='vnos',
            name='sprememba',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Sprememba'),
        ),
    ]
