# Generated by Django 2.2.5 on 2019-11-28 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0049_vnos_sprememba'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnevna_prodaja',
            name='skupna_cena',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='dnevna_prodaja',
            name='skupno_stevilo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sestavina',
            name='zaloga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Zaloga'),
        ),
    ]
