# Generated by Django 2.2.5 on 2019-12-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0050_auto_20191128_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontejner',
            name='drzava',
            field=models.CharField(choices=[('pan', 'Panama'), ('slo', 'Slovenija'), ('jap', 'Japonska'), ('pol', 'Poljska'), ('ang', 'Anglija'), ('kor', 'Korea')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='kontejner',
            name='posiljatelj',
            field=models.CharField(choices=[('bozo', 'Bozo'), ('japan', 'Japan')], default='', max_length=20),
        ),
    ]
