# Generated by Django 2.2.5 on 2019-12-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0051_auto_20191209_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontejner',
            name='drzava',
            field=models.CharField(choices=[('slo', 'Slovenia'), ('jap', 'Japan'), ('pol', 'Poland'), ('ang', 'England'), ('kor', 'Korea'), ('pan', 'Panama')], default='', max_length=20),
        ),
    ]
