# Generated by Django 2.2.5 on 2019-12-10 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zaloga', '0052_auto_20191209_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stroski_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20)),
                ('tip', models.CharField(default='', max_length=20)),
                ('datum', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='aktivno', max_length=20)),
                ('kontejner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Kontejner')),
            ],
        ),
        migrations.CreateModel(
            name='Strosek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20)),
                ('znesek', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('delavec', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Stroski_Group')),
            ],
        ),
    ]
