# Generated by Django 2.2.5 on 2020-01-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0054_auto_20191222_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaloga',
            name='tip',
            field=models.CharField(choices=[('dnevna_prodaja', 'Dnevna_prodaja'), ('vele_prodaja', 'Vele_prodaja')], default='vele_prodaja', max_length=20),
        ),
    ]
