# Generated by Django 2.2.5 on 2020-01-07 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0055_zaloga_tip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sestavina',
            name='dimenzija',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zaloga.Dimenzija'),
        ),
    ]
