# Generated by Django 2.2.5 on 2020-01-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0056_auto_20200107_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='cena',
            name='drzava',
            field=models.CharField(blank=True, choices=[('slo', 'Slovenia'), ('jap', 'Japan'), ('pol', 'Poland'), ('ang', 'England'), ('kor', 'Korea'), ('pan', 'Panama')], default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cena',
            name='nacin',
            field=models.CharField(choices=[('prodaja', 'Prodaja'), ('nakup', 'Nakup')], default='prodaja', max_length=10),
        ),
        migrations.AlterField(
            model_name='cena',
            name='prodaja',
            field=models.CharField(blank=True, choices=[('dnevna_prodaja', 'Dnevna_prodaja'), ('vele_prodaja', 'Vele_prodaja')], default=None, max_length=15, null=True),
        ),
    ]
