# Generated by Django 2.2.5 on 2020-01-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0058_auto_20200107_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaloga',
            name='tipi_prodaje',
            field=models.CharField(default="['vele_prodaja']", max_length=50),
        ),
    ]
