# Generated by Django 2.2.5 on 2020-01-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0059_auto_20200107_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaloga',
            name='tipi_prodaje',
            field=models.CharField(default='["vele_prodaja"]', max_length=50),
        ),
        migrations.AlterField(
            model_name='zaloga',
            name='tipi_sestavine',
            field=models.CharField(default='["Y","W","JP","JP50","JP70"]', max_length=50),
        ),
    ]
