# Generated by Django 2.2.5 on 2020-01-15 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zaloga', '0060_auto_20200107_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zaposleni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(default='', max_length=20)),
                ('priimek', models.CharField(default='', max_length=20)),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zaloga', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Zaloga')),
            ],
        ),
    ]
