# Generated by Django 2.2.5 on 2020-01-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0062_auto_20200115_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaposleni',
            name='davcna',
            field=models.CharField(default='/', max_length=30),
        ),
    ]
