# Generated by Django 2.2.5 on 2020-01-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0063_zaposleni_davcna'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaposleni',
            name='telefon',
            field=models.CharField(default='/', max_length=20),
        ),
    ]
