# Generated by Django 2.2.5 on 2020-01-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0064_zaposleni_telefon'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaposleni',
            name='mail',
            field=models.CharField(default='/', max_length=40),
        ),
    ]
