# Generated by Django 2.2.5 on 2020-01-15 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0065_zaposleni_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strosek',
            name='delavec',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Zaposleni'),
        ),
    ]
