# Generated by Django 2.2.5 on 2020-01-26 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0067_auto_20200115_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnevna_prodaja',
            name='skupna_cena',
        ),
        migrations.RemoveField(
            model_name='dnevna_prodaja',
            name='skupno_stevilo',
        ),
    ]
