# Generated by Django 2.2.5 on 2020-08-28 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0068_auto_20200126_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sestavina',
            name='zaklep_zaloge',
        ),
        migrations.AddField(
            model_name='zaloga',
            name='zaklep_zaloge',
            field=models.DateField(default=datetime.datetime(2019, 12, 6, 0, 0)),
        ),
        migrations.AlterField(
            model_name='sestavina',
            name='stanja_zaklepa',
            field=models.CharField(default="{'Y':0,'W':0,'JP':0,'JP50':0,'JP70':0}", max_length=100),
        ),
    ]
