# Generated by Django 2.2.5 on 2020-08-28 09:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0069_auto_20200828_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sestavina',
            name='stanja_zaklepa',
        ),
        migrations.RemoveField(
            model_name='zaloga',
            name='zaklep_zaloge',
        ),
        migrations.AlterField(
            model_name='baza',
            name='tip',
            field=models.CharField(choices=[('inventura', 'Inventura'), ('prevzem', 'Prevzem'), ('odpis', 'Odpis'), ('vele_prodaja', 'Vele prodaja'), ('racun', 'Racun'), ('narocilo', 'Narocilo'), ('zaklep', 'Zaklep')], default='prevzem', max_length=20),
        ),
        migrations.CreateModel(
            name='Zaklep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(default=datetime.datetime(2020, 8, 28, 11, 22, 31, 633959))),
                ('stanja_json', models.TextField(default='{}')),
                ('zaloga', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Zaloga')),
            ],
            options={
                'ordering': ['-datum'],
            },
        ),
    ]
