# Generated by Django 2.2.5 on 2020-08-28 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0070_auto_20200828_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaklep',
            name='datum',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
