# Generated by Django 2.2.5 on 2020-08-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0071_auto_20200828_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baza',
            name='tip',
            field=models.CharField(choices=[('inventura', 'Inventura'), ('prevzem', 'Prevzem'), ('odpis', 'Odpis'), ('vele_prodaja', 'Vele prodaja'), ('racun', 'Racun'), ('narocilo', 'Narocilo'), ('zaklep', 'Zaklep'), ('prenos', 'Prenos med skladišči')], default='prevzem', max_length=20),
        ),
    ]
