# Generated by Django 2.2.5 on 2020-09-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0072_auto_20200830_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baza',
            name='tip',
            field=models.CharField(choices=[('inventura', 'Inventura'), ('prevzem', 'Prevzem'), ('odpis', 'Odpis'), ('vele_prodaja', 'Vele prodaja'), ('racun', 'Racun'), ('narocilo', 'Narocilo'), ('prenos', 'Prenos med skladišči'), ('poslanPrenos', 'Poslan prenos med skladišči')], default='prevzem', max_length=20),
        ),
    ]
