# Generated by Django 2.2.5 on 2020-09-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0073_auto_20200928_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='baza',
            name='zalogaPrenosa',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
