# Generated by Django 2.2.16 on 2021-02-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0074_baza_zalogaprenosa'),
    ]

    operations = [
        migrations.AddField(
            model_name='baza',
            name='cena',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='baza',
            name='tip',
            field=models.CharField(choices=[('inventura', 'Inventura'), ('prevzem', 'Prevzem'), ('odpis', 'Odpis'), ('vele_prodaja', 'Vele prodaja'), ('racun', 'Racun'), ('narocilo', 'Narocilo'), ('prenos', 'Prenos med skladišči')], default='prevzem', max_length=20),
        ),
        migrations.AlterField(
            model_name='cena',
            name='drzava',
            field=models.CharField(blank=True, choices=[('slo', 'Slovenia'), ('jap', 'Japan'), ('pol', 'Poland'), ('ang', 'England'), ('kor', 'Korea'), ('pan', 'Panama'), ('swe', 'Sweden'), ('sui', 'Switzerland')], default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='kontejner',
            name='drzava',
            field=models.CharField(choices=[('slo', 'Slovenia'), ('jap', 'Japan'), ('pol', 'Poland'), ('ang', 'England'), ('kor', 'Korea'), ('pan', 'Panama'), ('swe', 'Sweden'), ('sui', 'Switzerland')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='kontejner',
            name='posiljatelj',
            field=models.CharField(choices=[('bozo', 'Bozo'), ('japan', 'Japan'), ('poland', 'Poland'), ('sweden', 'Sweden'), ('zoki', 'Zoki')], default='', max_length=20),
        ),
    ]
