# Generated by Django 2.2.16 on 2021-03-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0075_auto_20210201_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='vnos',
            name='cena_nakupa',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
    ]
