# Generated by Django 2.2.16 on 2021-05-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0076_vnos_cena_nakupa'),
    ]

    operations = [
        migrations.AddField(
            model_name='baza',
            name='ladijski_prevoz',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
