# Generated by Django 2.2.16 on 2021-06-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0077_baza_ladijski_prevoz'),
    ]

    operations = [
        migrations.AddField(
            model_name='baza',
            name='placilo',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
