# Generated by Django 2.2.16 on 2021-07-06 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0078_baza_placilo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kratko', models.CharField(default='', max_length=10)),
                ('dolgo', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sestavina',
            options={'ordering': ['zaloga', 'dimenzija', 'tip']},
        ),
        migrations.AddField(
            model_name='vnos',
            name='sestavina',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Sestavina'),
        ),
        migrations.AlterField(
            model_name='vnos',
            name='stevilo',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='VnosZaloge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stanje', models.IntegerField(default=0)),
                ('sestavina', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Sestavina')),
                ('zaloga', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Zaloga')),
            ],
        ),
        migrations.AddField(
            model_name='sestavina',
            name='tip',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Tip'),
        ),
    ]
