# Generated by Django 2.2.16 on 2021-07-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0078_baza_placilo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baza',
            options={'permissions': [('view_json', 'Can view JSON')]},
        ),
        migrations.AlterModelOptions(
            name='dnevna_prodaja',
            options={'permissions': [('view_json', 'Can view JSON')]},
        ),
    ]
