# Generated by Django 3.2.8 on 2022-04-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0079_auto_20210715_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='baza',
            name='ladjar',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='baza',
            name='predviden_prihod',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
