# Generated by Django 3.2.8 on 2022-04-09 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0080_auto_20220409_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baza',
            old_name='predviden_prihod',
            new_name='datum_prihoda',
        ),
    ]
