# Generated by Django 2.2.16 on 2021-07-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0080_auto_20210706_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sestavina',
            name='zaloga',
        ),
        migrations.AddField(
            model_name='zaloga',
            name='cenik',
            field=models.ManyToManyField(to='zaloga.Cena'),
        ),
        migrations.AddField(
            model_name='zaloga',
            name='sestavine',
            field=models.ManyToManyField(to='zaloga.Sestavina'),
        ),
        migrations.AddField(
            model_name='zaloga',
            name='tipi_sestavin',
            field=models.ManyToManyField(to='zaloga.Tip'),
        ),
    ]
