# Generated by Django 3.2.16 on 2022-10-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0081_rename_predviden_prihod_baza_datum_prihoda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baza',
            name='tip',
            field=models.CharField(choices=[('inventura', 'Inventura'), ('prevzem', 'Prevzem'), ('odpis', 'Odpis'), ('vele_prodaja', 'Vele prodaja'), ('racun', 'Racun'), ('narocilo', 'Narocilo'), ('prenos', 'Prenos med skladišči'), ('ribce', 'Ribce')], default='prevzem', max_length=20),
        ),
        migrations.AlterField(
            model_name='kontejner',
            name='posiljatelj',
            field=models.CharField(choices=[('bozo', 'Bozo'), ('dob', 'Dobova - Brežice'), ('japan', 'Japan'), ('poland', 'Poland'), ('sweden', 'Sweden'), ('zoki', 'Zoki')], default='', max_length=20),
        ),
    ]
