# Generated by Django 2.2.16 on 2021-07-06 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0081_auto_20210706_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sestavina',
            name='JP',
        ),
        migrations.RemoveField(
            model_name='sestavina',
            name='JP50',
        ),
        migrations.RemoveField(
            model_name='sestavina',
            name='JP70',
        ),
        migrations.RemoveField(
            model_name='sestavina',
            name='W',
        ),
        migrations.RemoveField(
            model_name='sestavina',
            name='Y',
        ),
    ]
