# Generated by Django 3.2.8 on 2023-02-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0082_auto_20221019_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimenzija',
            name='diameter',
            field=models.IntegerField(default=0),
        ),
    ]
