# Generated by Django 2.2.16 on 2021-07-06 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0083_auto_20210706_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vnos',
            name='baza',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Baza'),
        ),
    ]
