# Generated by Django 2.2.16 on 2021-07-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0084_auto_20210706_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vnos',
            name='dimenzija',
        ),
        migrations.RemoveField(
            model_name='vnos',
            name='tip',
        ),
    ]
