# Generated by Django 2.2.16 on 2021-07-17 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0086_auto_20210713_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnevna_prodaja',
            name='prodaja',
        ),
    ]
