# Generated by Django 2.2.16 on 2021-07-17 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0010_auto_20210717_2241'),
        ('zaloga', '0087_remove_dnevna_prodaja_prodaja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dobavitelj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podjetje', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='program.Podjetje')),
            ],
        ),
    ]
