# Generated by Django 2.2.16 on 2021-07-17 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0088_dobavitelj'),
    ]

    operations = [
        migrations.AddField(
            model_name='baza',
            name='dobavitelj',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='zaloga.Dobavitelj'),
        ),
    ]
