# Generated by Django 2.2.16 on 2021-07-20 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0089_baza_dobavitelj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kontejner',
            name='drzava',
        ),
        migrations.RemoveField(
            model_name='kontejner',
            name='posiljatelj',
        ),
    ]
