# Generated by Django 2.2.16 on 2021-07-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0090_auto_20210720_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='baza',
            name='stevilka',
            field=models.IntegerField(default=0),
        ),
    ]
