# Generated by Django 2.2.16 on 2021-07-20 18:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0091_baza_stevilka'),
    ]

    operations = [
        migrations.AddField(
            model_name='baza',
            name='cas_uveljavitve',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
