# Generated by Django 2.2.16 on 2021-07-20 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0092_baza_cas_uveljavitve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baza',
            name='cas',
        ),
    ]
