# Generated by Django 2.2.16 on 2021-07-31 06:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0093_remove_baza_cas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baza',
            old_name='cas_uveljavitve',
            new_name='uveljavitev',
        ),
        migrations.AddField(
            model_name='baza',
            name='odprema_blaga',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
