# Generated by Django 2.2.16 on 2021-07-31 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0094_auto_20210731_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baza',
            name='datum',
        ),
    ]
