# Generated by Django 2.2.16 on 2021-07-31 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0095_remove_baza_datum'),
    ]

    operations = [
        migrations.AddField(
            model_name='baza',
            name='datum',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
