# Generated by Django 2.2.16 on 2021-07-31 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0096_baza_datum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cena',
            name='drzava',
        ),
        migrations.RemoveField(
            model_name='cena',
            name='nacin',
        ),
        migrations.RemoveField(
            model_name='cena',
            name='prodaja',
        ),
        migrations.RemoveField(
            model_name='cena',
            name='tip',
        ),
    ]
