# Generated by Django 2.2.16 on 2021-07-31 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0097_auto_20210731_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zaloga',
            name='tipi_prodaje',
        ),
        migrations.RemoveField(
            model_name='zaloga',
            name='tipi_sestavine',
        ),
    ]
