# Generated by Django 2.2.16 on 2021-07-31 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0011_auto_20210731_2033'),
        ('zaloga', '0098_auto_20210731_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zaposleni',
            name='davcna',
        ),
        migrations.RemoveField(
            model_name='zaposleni',
            name='ime',
        ),
        migrations.RemoveField(
            model_name='zaposleni',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='zaposleni',
            name='naslov',
        ),
        migrations.RemoveField(
            model_name='zaposleni',
            name='priimek',
        ),
        migrations.RemoveField(
            model_name='zaposleni',
            name='telefon',
        ),
        migrations.RemoveField(
            model_name='zaposleni',
            name='zaloga',
        ),
        migrations.AddField(
            model_name='zaposleni',
            name='oseba',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.Oseba'),
        ),
        migrations.DeleteModel(
            name='Zaklep',
        ),
    ]
