# Generated by Django 2.2.16 on 2021-08-01 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0099_auto_20210731_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vnos',
            name='sprememba',
        ),
        migrations.DeleteModel(
            name='Sprememba',
        ),
    ]
