# Generated by Django 2.2.16 on 2021-08-01 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0011_auto_20210731_2033'),
        ('zaloga', '0100_auto_20210801_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zaloga',
            name='cenik',
        ),
        migrations.CreateModel(
            name='Stranka2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='aktivno', max_length=10)),
                ('podjetje', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.Podjetje')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cenik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(default='vele_prodaja', max_length=20)),
                ('cene', models.ManyToManyField(to='zaloga.Cena')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='zaloga',
            name='ceniki',
            field=models.ManyToManyField(to='zaloga.Cenik'),
        ),
    ]
