# Generated by Django 2.2.16 on 2021-08-01 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0102_cena_valuta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cena',
            name='valuta',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='program.Valuta'),
        ),
    ]
