# Generated by Django 2.2.16 on 2021-08-01 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0103_auto_20210801_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cena',
            name='valuta',
        ),
    ]
