# Generated by Django 2.2.16 on 2021-08-01 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0012_valuta'),
        ('zaloga', '0104_remove_cena_valuta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cena',
            name='valuta2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='program.Valuta'),
        ),
    ]
