# Generated by Django 2.2.16 on 2021-08-01 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0105_cena_valuta2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cena',
            name='valuta2',
        ),
    ]
