# Generated by Django 2.2.16 on 2021-08-01 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0012_valuta'),
        ('zaloga', '0106_remove_cena_valuta2'),
    ]

    operations = [
        migrations.AddField(
            model_name='cena',
            name='valuta',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='program.Valuta'),
        ),
    ]
