# Generated by Django 2.2.16 on 2021-08-01 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0107_cena_valuta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baza',
            name='tip',
            field=models.CharField(choices=[('inventura', 'Inventura'), ('prevzem', 'Prevzem'), ('prevzem_prenosa', 'Prevzem prenosa'), ('odpis', 'Odpis'), ('vele_prodaja', 'Vele prodaja'), ('racun', 'Racun'), ('narocilo', 'Narocilo'), ('prenos', 'Prenos med skladišči')], default='prevzem', max_length=20),
        ),
        migrations.AlterField(
            model_name='cena',
            name='valuta',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='program.Valuta'),
        ),
    ]
