# Generated by Django 2.2.16 on 2021-08-08 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0108_auto_20210801_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='baza',
            name='narocilo',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zaloga.Baza'),
        ),
    ]
