# Generated by Django 2.2.16 on 2021-08-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0109_baza_narocilo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimenzija',
            name='visinaSpecial',
            field=models.CharField(default='', max_length=10),
        ),
    ]
