# Generated by Django 2.2.16 on 2021-08-11 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0110_dimenzija_visinaspecial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimenzija',
            options={'ordering': ['radij', 'height', 'width', 'special']},
        ),
        migrations.RenameField(
            model_name='dimenzija',
            old_name='radius',
            new_name='radij',
        ),
    ]
