# Generated by Django 2.2.16 on 2021-08-11 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0111_auto_20210811_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimenzija',
            options={'ordering': ['radij', 'visina', 'width', 'special']},
        ),
        migrations.RenameField(
            model_name='dimenzija',
            old_name='height',
            new_name='visina',
        ),
    ]
