# Generated by Django 2.2.16 on 2021-08-11 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0112_auto_20210811_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimenzija',
            options={'ordering': ['radij', 'visina', 'sirina', 'special']},
        ),
        migrations.RenameField(
            model_name='dimenzija',
            old_name='width',
            new_name='sirina',
        ),
    ]
