# Generated by Django 2.2.16 on 2021-08-11 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0113_auto_20210811_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimenzija',
            options={'ordering': ['radij', 'sirina', 'visina', 'special']},
        ),
        migrations.RenameField(
            model_name='dimenzija',
            old_name='visinaSpecial',
            new_name='visina_special',
        ),
    ]
