# Generated by Django 2.2.16 on 2021-08-12 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0114_auto_20210811_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='baza',
            name='stranka2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zaloga.Stranka2'),
        ),
    ]
