# Generated by Django 2.2.16 on 2021-08-12 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0115_baza_stranka2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baza',
            name='stranka',
        ),
    ]
