# Generated by Django 2.2.16 on 2021-08-12 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0116_remove_baza_stranka'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baza',
            old_name='stranka2',
            new_name='stranka',
        ),
    ]
