# Generated by Django 2.2.16 on 2021-08-12 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0013_remove_profil_stranka'),
        ('zaloga', '0117_auto_20210812_2010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stranka2',
            new_name='Stranka',
        ),
    ]
