# Generated by Django 2.2.16 on 2021-08-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0118_auto_20210812_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='stranka',
            name='narocila',
            field=models.ManyToManyField(related_name='stranka_model', to='zaloga.Baza'),
        ),
    ]
