# Generated by Django 2.2.16 on 2021-09-12 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaloga', '0119_stranka_narocila'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stranka',
            name='narocila',
        ),
    ]
